name: travel_planner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.4.2
  country_picker: ^2.0.27
  intl: ^0.20.2
  google_fonts: ^6.3.2
  google_mobile_ads: ^6.0.0
  firebase_core: ^4.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
