// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeLuOd7IVT4SPikTqkZcJ-gPQULwoc8kw',
    appId: '1:891605876777:web:ec2d15fe32cfb14ef81c38',
    messagingSenderId: '891605876777',
    projectId: 'travel-planner-hongdroid',
    authDomain: 'travel-planner-hongdroid.firebaseapp.com',
    storageBucket: 'travel-planner-hongdroid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpDHuN_apZVONzShiRx6D6wIo62gFJQsU',
    appId: '1:891605876777:android:22d3155f47efec69f81c38',
    messagingSenderId: '891605876777',
    projectId: 'travel-planner-hongdroid',
    storageBucket: 'travel-planner-hongdroid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDUSTTYSRZEsDhIbx-2Ade__Ror-MFbMg',
    appId: '1:891605876777:ios:754441e82de6a336f81c38',
    messagingSenderId: '891605876777',
    projectId: 'travel-planner-hongdroid',
    storageBucket: 'travel-planner-hongdroid.firebasestorage.app',
    iosBundleId: 'yes',
  );
}
