// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxSyHAfpXVukdhalx0ea93cnwnEFR4du4',
    appId: '1:361922934819:web:57e56c3db9c88b5d1c9996',
    messagingSenderId: '361922934819',
    projectId: 'travel-planner-148a2',
    authDomain: 'travel-planner-148a2.firebaseapp.com',
    storageBucket: 'travel-planner-148a2.firebasestorage.app',
    measurementId: 'G-M7D134EPB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFIUVBZtZBzyvOlbW53X6z5eXwHn49qL8',
    appId: '1:361922934819:android:d66ed79b1c03e3791c9996',
    messagingSenderId: '361922934819',
    projectId: 'travel-planner-148a2',
    storageBucket: 'travel-planner-148a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAYOI7ysx6ob3uaEhWs_ZibWiIjDPTRQw',
    appId: '1:361922934819:ios:24d1f3148a949d861c9996',
    messagingSenderId: '361922934819',
    projectId: 'travel-planner-148a2',
    storageBucket: 'travel-planner-148a2.firebasestorage.app',
    iosBundleId: 'yes',
  );

}